#!/bin/sh
EMAIL=$(git config user.email)

validate_company_domain() {
    if [[ $EMAIL == *"@fusemachines.com"* ]]; then
        echo "[INFO] Verified email: $EMAIL"
    else
        echo "[ERROR] Invalid email domain: $EMAIL"
        echo "[ERROR] Please configure the company email and retry."
        echo "For this, do the following:"
        echo "   git config user.email \"your.name@fusemachines.com\""
        exit 1
    fi
}

# Check for trailing whitespaces
check_trailing_whitespace() {
    local files_with_trailing_ws=$(git diff --check --cached | grep -E "^\+.*[[:space:]]+$")
    if [ -n "$files_with_trailing_ws" ]; then
        echo "[ERROR] Trailing whitespaces detected in the following files:"
        echo "$files_with_trailing_ws"
        echo "[ERROR] Remove the trailing whitespaces before committing."
        exit 1
    fi
}

# Validate company domain
validate_company_domain
# Check for trailing whitespaces
check_trailing_whitespace
# Exit successfully
exit 0
